[package]
name = "bfuck"
version = "0.2.0"
authors = ["Antonio Mamić <antoniomamic007@gmail.com>"]
edition = "2024"
description = "A simple Brainfuck interpreter, JIT-compiler and compiler"
readme = "README.md"
repository = "https://github.com/amamic1803/bfuck-rs"
license = "MIT"
keywords = ["cli", "interpreter", "jit", "compiler"]
categories = ["command-line-interface", "compilers"]
include = [
    "/.cargo",
    "/src",
    "/examples",
    "/tests",
    "Cargo.toml",
    "LICENSE",
    "README.md",
]


[profile.release]
lto = true


[profile.test]
opt-level = 3


[dependencies]
clap = {version = "4.6.1", features = ["cargo"]}
cranelift = "0.133.1"
memmap2 = "0.9.11"
target-lexicon = "0.13.5"


[dev-dependencies]
assert_cmd = "2.2.2"
predicates = "3.1.4"
